In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("D:/Microsoft Data Engineer/Graduation Project/Database/cleaned_online_retail.csv")

In [2]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Total,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,15.30,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,20.34,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,22.00,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,20.34,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,20.34,17850.0,United Kingdom,20.34

In [5]:
# Create customers.csv
customers = df[['CustomerID', 'Country']].drop_duplicates(subset=['CustomerID'])
customers.to_csv('D:/Microsoft Data Engineer/Graduation Project/Database/customers.csv', index=False)

# Create products.csv
products = df[['StockCode', 'Description', 'UnitPrice']].drop_duplicates(subset=['StockCode'])
products.to_csv('D:/Microsoft Data Engineer/Graduation Project/Database/products.csv', index=False)

# Create invoices.csv
invoices = df[['InvoiceNo', 'CustomerID', 'InvoiceDate']].drop_duplicates(subset=['InvoiceNo'])
invoices.to_csv('D:/Microsoft Data Engineer/Graduation Project/Database/invoices.csv', index=False)

# Create invoice_items.csv (ensure all InvoiceNo values exist in invoices.csv)
invoice_items = df[['InvoiceNo', 'StockCode', 'Quantity', 'TotalPrice']]
invoice_items = invoice_items[invoice_items['InvoiceNo'].isin(invoices['InvoiceNo'])]
invoice_items.to_csv('D:/Microsoft Data Engineer/Graduation Project/Database/invoice_items.csv', index=False)